#!/usr/bin/env python3
"""
Generate 005_seed_vendors.sql from Bonnie's QBO vendor exports.
One-time script — run once, output is committed as a migration.

Usage: python3 scripts/generate-vendor-seed.py
"""

import openpyxl
import os
import re

DOCS_DIR = os.path.join(os.path.dirname(__file__), '..', 'docs', 'FromBonnie')
OUTPUT = os.path.join(os.path.dirname(__file__), '..', 'supabase', 'migrations', '005_seed_vendors.sql')


def read_vendors(filename):
    """Read vendors from an Excel file. Returns list of dicts."""
    path = os.path.join(DOCS_DIR, filename)
    wb = openpyxl.load_workbook(path)
    ws = wb.active
    vendors = []
    for row in ws.iter_rows(min_row=5, values_only=True):  # skip header rows
        name = row[0]
        if not name or str(name).strip() == '' or str(name).strip() == 'TOTAL':
            continue
        name = str(name).strip()
        # Extract phone — strip "Phone:" prefix and "Fax:..." suffix
        phone = None
        if row[1]:
            phone_raw = str(row[1]).strip()
            # Extract first phone number
            match = re.search(r'Phone:\s*([\d\-() ]+)', phone_raw)
            if match:
                phone = re.sub(r'[^0-9]', '', match.group(1))
                if len(phone) == 10:
                    phone = f"({phone[:3]}) {phone[3:6]}-{phone[6:]}"
                elif len(phone) == 11 and phone[0] == '1':
                    phone = f"({phone[1:4]}) {phone[4:7]}-{phone[7:]}"
                else:
                    phone = phone_raw.split('Fax')[0].replace('Phone:', '').strip()
            else:
                digits = re.sub(r'[^0-9]', '', phone_raw)
                if len(digits) == 10:
                    phone = f"({digits[:3]}) {digits[3:6]}-{digits[6:]}"
                elif phone_raw.strip():
                    phone = phone_raw.split('Fax')[0].strip()[:50]

        email = str(row[2]).strip() if row[2] and str(row[2]).strip() else None
        address = str(row[4]).strip() if row[4] and str(row[4]).strip() else None

        vendors.append({
            'name': name,
            'phone': phone,
            'email': email,
            'address': address,
        })
    return vendors


def escape_sql(val):
    """Escape a string for SQL insertion."""
    if val is None:
        return 'null'
    # Escape single quotes
    escaped = val.replace("'", "''")
    return f"'{escaped}'"


def main():
    print("Reading CC vendors...")
    cc_vendors = read_vendors('CC Vendor list.xlsx')
    print(f"  Found {len(cc_vendors)} CC vendors")

    print("Reading NSCC vendors...")
    nscc_vendors = read_vendors('NSCC Vendor list.xlsx')
    print(f"  Found {len(nscc_vendors)} NSCC vendors")

    # Find overlapping vendors (case-insensitive name match)
    cc_names = {v['name'].lower(): v for v in cc_vendors}
    nscc_names = {v['name'].lower(): v for v in nscc_vendors}
    shared_names = set(cc_names.keys()) & set(nscc_names.keys())
    print(f"  Shared vendors: {len(shared_names)}")

    lines = []
    lines.append("-- Migration 005: Seed vendors from Bonnie's QBO exports (April 2026)")
    lines.append("-- Generated by scripts/generate-vendor-seed.py")
    lines.append(f"-- CC vendors: {len(cc_vendors)}, NSCC vendors: {len(nscc_vendors)}, Shared: {len(shared_names)}")
    lines.append("")
    lines.append("begin;")
    lines.append("")

    # Shared vendors (entity = NULL)
    lines.append("-- ============================================================")
    lines.append(f"-- SHARED VENDORS (appear in both CC and NSCC) — {len(shared_names)} vendors")
    lines.append("-- ============================================================")
    lines.append("")
    for name_lower in sorted(shared_names):
        v = cc_names[name_lower]  # use CC data as primary (likely more complete)
        nscc_v = nscc_names[name_lower]
        # Merge: prefer non-null values
        phone = v['phone'] or nscc_v['phone']
        email = v['email'] or nscc_v['email']
        address = v['address'] or nscc_v['address']
        lines.append(
            f"insert into public.vendors (name, phone, email, address, entity, is_active) "
            f"values ({escape_sql(v['name'])}, {escape_sql(phone)}, {escape_sql(email)}, "
            f"{escape_sql(address)}, null, true);"
        )

    # CC-only vendors
    cc_only = [v for v in cc_vendors if v['name'].lower() not in shared_names]
    lines.append("")
    lines.append("-- ============================================================")
    lines.append(f"-- CHRIST CHURCH VENDORS (CC only) — {len(cc_only)} vendors")
    lines.append("-- ============================================================")
    lines.append("")
    for v in sorted(cc_only, key=lambda x: x['name'].lower()):
        lines.append(
            f"insert into public.vendors (name, phone, email, address, entity, is_active) "
            f"values ({escape_sql(v['name'])}, {escape_sql(v['phone'])}, {escape_sql(v['email'])}, "
            f"{escape_sql(v['address'])}, 'church', true);"
        )

    # NSCC-only vendors
    nscc_only = [v for v in nscc_vendors if v['name'].lower() not in shared_names]
    lines.append("")
    lines.append("-- ============================================================")
    lines.append(f"-- NSCC VENDORS (NSCC only) — {len(nscc_only)} vendors")
    lines.append("-- ============================================================")
    lines.append("")
    for v in sorted(nscc_only, key=lambda x: x['name'].lower()):
        lines.append(
            f"insert into public.vendors (name, phone, email, address, entity, is_active) "
            f"values ({escape_sql(v['name'])}, {escape_sql(v['phone'])}, {escape_sql(v['email'])}, "
            f"{escape_sql(v['address'])}, 'nscc', true);"
        )

    lines.append("")
    lines.append("commit;")
    lines.append("")

    with open(OUTPUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    total = len(shared_names) + len(cc_only) + len(nscc_only)
    print(f"\nWrote {OUTPUT}")
    print(f"Total vendors: {total} ({len(shared_names)} shared + {len(cc_only)} CC + {len(nscc_only)} NSCC)")


if __name__ == '__main__':
    main()
